### PR TITLE
Updated Create_CTC_Query_FST.sh so that starting and ending delimiters can be different

### PR DESCRIPTION
**Pull request by mauvilsa**

### CODE REVIEW

**Comment by jpuigcerver** [comment]
I don't see the need of using different delimiters types for the query. Notice that the result of the intersection between the language represented by the Query FST that you are just creating and the one that was being created before would be the same...

**Comment by jpuigcerver** [comment]
My point is that, in practice: The intersection between the line lattice (L) and the result of `old_script.sh --delimiters "<s> </s> @"` would give the same as the intersection of L and the result of `new_script.sh --start_delimiters "<s> @" --end_delimiters "</s> @"`

**Comment by mauvilsa** [comment]
Are you sure it gives the same result? For example start-delimiters="{space} (" and end-delimiters="{space} . , : - ) /" should mean that a word can be preceded only by a space or '(' or at the start of the line and that it can end with several other additional symbols excluding '(' or at the end of the line. The queries are different if the same symbols are allowed at the start and the end.

Doing a small experiment the results are different and an important difference is the computation time: 323 vs. 248 seconds.

**Comment by jpuigcerver** [comment]
Ok. They are equivalent for my typical use cases, but you are right in your counter-example. Accepting PR.

**Pull request merged**
